name: Terraform CI

on:
  pull_request:

jobs:
  ci:
    uses: ${{ github.repository_owner }}/github-actions-workflows/.github/workflows/terraform_ci.yml@main
    with:
      terraform_version: 1.1.2
