name: Terraform CI

on:
  pull_request:

jobs:
  fmt:
    runs-on: ubuntu-20.04

    env:
      TF_VERSION: 1.1.2

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - run: git diff origin/main...HEAD --diff-filter=d --name-only | grep -E "\.tf$"

      - name: terraform fmt only created or updated *.tf
        run: |
          set -euo pipefail

          files=($(git diff origin/main...HEAD --diff-filter=d --name-only | grep -E "\.tf$"))

          for file in "${file[@]}"
          do
            result+=$(terraform fmt -list=false -diff -write=false "$file")
          done

          if [ -n "$result" ]; then
            echo "$result"
            exit 1
          fi
        shell: bash
